import type { Metadata } from "next";
import { Sofia_Sans } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { HydrateStores } from "@/store/HydrateStores";
import { CraftingTreeHoverProvider } from "@/context/crafting-tree-hover";

const sofiaSans = Sofia_Sans({
  variable: "--font-sofia-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sofiaSans.variable} antialiased dark`}>
        <CraftingTreeHoverProvider>
          {children}
          <HydrateStores />
          <Analytics />
          <SpeedInsights />
        </CraftingTreeHoverProvider>
      </body>
    </html>
  );
}
